global:
  scrape_interval: 15s

scrape_configs:
<<<<<<< HEAD
  - job_name: 'prediction-api'
    static_configs:
      - targets: ['prediction-api:8000']

  - job_name: 'training-api'
    static_configs:
      - targets: ['training-api:8001']
=======

  - job_name: "prediction-api"
    static_configs:
      - targets: ["prediction-api:8000"]

  - job_name: "training-api"
    static_configs:
      - targets: ["training-api:8001"]
>>>>>>> 07750723e56885fdab2c3c986d5e9b507b07559f
